import type { DocumentRecord } from "@/types/documents";

export const mockDocuments: DocumentRecord[] = [
  {
    id: "1",
    title: "Annual Physical Examination Summary",
    type: "Visit Summary",
    date: "2024-01-15",
    status: "Available",
    source: "CareOS",
    fileName: "annual-physical-2024.pdf",
    notes: "Complete annual physical examination results",
    tags: ["Annual", "Physical"],
  },
  {
    id: "2",
    title: "Blood Work Results - CBC Panel",
    type: "Lab Result",
    date: "2024-01-10",
    status: "Available",
    source: "Quest Diagnostics",
    fileName: "cbc-panel-2024.pdf",
    tags: ["Lab", "CBC"],
  },
  {
    id: "3",
    title: "Care Plan - Home Health Services",
    type: "Plan of Care",
    date: "2024-01-08",
    status: "Available",
    source: "CareOS",
    fileName: "care-plan-2024.pdf",
    notes: "Updated care plan for home health services",
    tags: ["Care Plan", "Home Health"],
  },
  {
    id: "4",
    title: "Medication Reconciliation Form",
    type: "Other",
    date: "2024-01-05",
    status: "Available",
    source: "CareOS",
    fileName: "med-reconciliation.pdf",
    tags: ["Medication"],
  },
  {
    id: "5",
    title: "January Billing Statement",
    type: "Billing",
    date: "2024-01-20",
    status: "Pending",
    source: "Billing Department",
    fileName: "billing-jan-2024.pdf",
    notes: "Pending insurance review",
  },
  {
    id: "6",
    title: "X-Ray Results - Chest",
    type: "Lab Result",
    date: "2024-01-18",
    status: "Processing",
    source: "Medical Imaging Center",
    notes: "X-ray results being processed",
  },
  {
    id: "7",
    title: "Home Visit Summary - Week 1",
    type: "Visit Summary",
    date: "2024-01-12",
    status: "Available",
    source: "CareOS",
    fileName: "home-visit-wk1.pdf",
    tags: ["Home Visit"],
  },
  {
    id: "8",
    title: "Insurance Claim - January",
    type: "Billing",
    date: "2024-01-22",
    status: "Rejected",
    source: "Billing Department",
    notes: "Claim rejected - requires additional documentation",
    tags: ["Insurance", "Claim"],
  },
  {
    id: "9",
    title: "Physical Therapy Assessment",
    type: "Plan of Care",
    date: "2024-01-14",
    status: "Available",
    source: "Physical Therapy Services",
    fileName: "pt-assessment.pdf",
    tags: ["Physical Therapy"],
  },
  {
    id: "10",
    title: "Lab Results - Lipid Panel",
    type: "Lab Result",
    date: "2024-01-09",
    status: "Available",
    source: "Quest Diagnostics",
    fileName: "lipid-panel-2024.pdf",
    tags: ["Lab", "Cholesterol"],
  },
  {
    id: "11",
    title: "Discharge Summary - Hospital Stay",
    type: "Visit Summary",
    date: "2024-01-03",
    status: "Available",
    source: "Hospital System",
    fileName: "discharge-summary.pdf",
    notes: "Discharge summary from recent hospitalization",
    tags: ["Hospital", "Discharge"],
  },
  {
    id: "12",
    title: "Medication List Update",
    type: "Other",
    date: "2024-01-19",
    status: "Processing",
    source: "CareOS",
    notes: "Medication list being updated",
  },
];
