/**
 * Phase 18.2 – Human-readable report formatter
 *
 * Produces plain-text reports for parents (e.g. at Walgreens) instead of raw JSON.
 */

export interface ReportData {
  meta: {
    checkId: string;
    profileId: string;
    createdAt: string;
    taxonomyVersion?: string | null;
  };
  input: {
    events: Array<{
      event_type: string;
      event_data: Record<string, unknown>;
    }>;
    rawText?: string;
  };
  output: {
    verdict: {
      riskLevel: string;
      meta: { severity?: number };
      matched: Array<{
        kind: string;
        ruleCode?: string | null;
        matchedTerm: string;
        matchedCategory?: string;
        crossReactive?: boolean;
        details?: Record<string, unknown>;
      }>;
    };
  };
  profile?: {
    name: string;
    allergies: string[];
    medications: string[];
    supplements: string[];
  };
}

/** Raw match from DB (has full details before filtering). */
export interface RawMatch {
  rule: string;
  ruleCode?: string;
  details: Record<string, unknown>;
}

export function formatReportAsText(
  data: ReportData,
  options: {
    includeOriginalText?: boolean;
    /** Use raw matched (full details) instead of report's filtered matched. */
    rawMatched?: RawMatch[];
  } = {}
): string {
  const { includeOriginalText = false, rawMatched } = options;
  const lines: string[] = [];
  const divider = "════════════════════════════════════════════════════════════";
  const thinDivider = "────────────────────────────────────────────────────────────";

  // Header
  lines.push(divider);
  lines.push("                    ALLERGY ANGEL REPORT");
  lines.push(divider);
  lines.push("");

  // Meta
  const date = new Date(data.meta.createdAt);
  const formattedDate = date.toLocaleDateString("en-US", {
    weekday: "short",
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  lines.push(`Check Date:     ${formattedDate}`);
  lines.push(`Profile:        ${data.profile?.name ?? "Unknown"}`);
  lines.push(`Risk Level:     ${formatRiskLevel(data.output.verdict.riskLevel)}`);
  lines.push("");

  // What you checked
  lines.push(thinDivider);
  lines.push("WHAT YOU CHECKED");
  lines.push(thinDivider);
  lines.push("");

  if (includeOriginalText && data.input.rawText) {
    lines.push(`"${data.input.rawText}"`);
  } else if (data.input.rawText) {
    lines.push("[Original text redacted for privacy]");
  } else {
    lines.push("[No original text recorded]");
  }
  lines.push("");

  lines.push("Events detected:");
  const events = data.input.events ?? [];
  if (events.length === 0) {
    lines.push("  (none)");
  } else {
    for (const event of events) {
      const type = capitalizeFirst(event.event_type);
      const description = getEventDescription(event);
      lines.push(`  • [${type}] ${description}`);
    }
  }
  lines.push("");

  // Why it's risky
  lines.push(thinDivider);
  lines.push("WHY IT'S RISKY");
  lines.push(thinDivider);
  lines.push("");

  const matched = rawMatched ?? data.output.verdict.matched ?? [];
  if (matched.length === 0) {
    lines.push("  No risks detected.");
  } else {
    for (const m of matched) {
      const entry = isRawMatch(m)
        ? { kind: m.rule, matchedTerm: extractMatchedTerm(m), matchedCategory: extractCategory(m), details: m.details }
        : m;
      lines.push(formatMatch(entry));
      lines.push("");
    }
  }

  // Recommendation
  lines.push(thinDivider);
  lines.push("RECOMMENDATION");
  lines.push(thinDivider);
  lines.push("");
  lines.push(getRecommendation(data.output.verdict.riskLevel));
  lines.push("");

  // Profile summary
  if (data.profile) {
    lines.push(thinDivider);
    lines.push("PROFILE SUMMARY");
    lines.push(thinDivider);
    lines.push("");
    const allergies = data.profile.allergies?.length
      ? data.profile.allergies.join(", ")
      : "None";
    const meds = data.profile.medications?.length
      ? data.profile.medications.join(", ")
      : "None";
    const supps = data.profile.supplements?.length
      ? data.profile.supplements.join(", ")
      : "None";
    lines.push(`Allergies:      ${allergies}`);
    lines.push(`Medications:    ${meds}`);
    lines.push(`Supplements:    ${supps}`);
    lines.push("");
  }

  // Footer
  lines.push(divider);
  lines.push("Generated by Allergy Angel");
  lines.push(new Date().toISOString());
  lines.push("");
  lines.push("⚠️  This is not medical advice. Always consult a healthcare");
  lines.push("    provider for medical decisions.");
  lines.push(divider);

  return lines.join("\n");
}

function formatRiskLevel(level: string): string {
  switch (level?.toLowerCase()) {
    case "high":
      return "⚠️ HIGH RISK";
    case "medium":
      return "⚡ MEDIUM RISK";
    case "low":
    case "caution":
      return "💡 CAUTION";
    case "none":
    case "safe":
      return "✅ SAFE";
    default:
      return level ? level.toUpperCase() : "—";
  }
}

function capitalizeFirst(str: string): string {
  return str ? str.charAt(0).toUpperCase() + str.slice(1) : "";
}

function getEventDescription(event: {
  event_type: string;
  event_data: Record<string, unknown>;
}): string {
  const d = event.event_data ?? {};
  switch (event.event_type) {
    case "meal":
      return String(d.meal ?? d.description ?? "Unknown meal");
    case "supplement":
      return String(d.supplement ?? d.name ?? "Unknown supplement");
    case "medication":
      return String(d.medication ?? d.name ?? "Unknown medication");
    case "symptom":
      return String(d.symptom ?? "Unknown symptom");
    case "glucose":
      return `${d.value ?? "—"} ${d.unit ?? "mg/dL"}`.trim();
    default:
      if (d.text) return String(d.text);
      if (d.name) return String(d.name);
      return JSON.stringify(d) || "—";
  }
}

function formatMatch(match: {
  kind: string;
  matchedTerm: string;
  matchedCategory?: string;
  details?: Record<string, unknown>;
}): string {
  const d = match.details ?? {};

  switch (match.kind) {
    case "allergy_match": {
      const term = String(d.allergen ?? match.matchedTerm ?? "ingredient");
      const meal = String(d.meal ?? "");
      const severity = d.severity != null ? `${d.severity}/100` : "Unknown";
      return `  • "${meal || term}" matches your ${term} allergy\n    - Severity: ${severity}`;
    }

    case "dish_allergen": {
      const dish = String(d.matchedDish ?? match.matchedTerm ?? "This dish");
      const allergen = String(d.allergen ?? match.matchedCategory ?? "allergen");
      const severity = d.severity != null ? `${d.severity}/100` : "Unknown";
      return `  • "${dish}" commonly contains ${allergen}\n    - Matched: ${allergen} allergy\n    - Severity: ${severity}`;
    }

    case "cross_reactive": {
      const term = String(d.matchedTerm ?? match.matchedTerm ?? "ingredient");
      const source = String(d.source ?? match.matchedCategory ?? "your allergies");
      const sourceDisplay = source.replace(/_/g, " ");
      return `  • "${term}" may cross-react with ${sourceDisplay}\n    - This is a potential sensitivity, not a confirmed allergy`;
    }

    case "supplement_medication_interaction": {
      const supp = String(d.supplement ?? match.matchedTerm ?? "supplement");
      const med = String(d.medication ?? "your medication");
      const risk = String(d.risk ?? "Unknown");
      const reason = String(d.reason ?? "Consult your pharmacist");
      return `  • "${supp}" may interact with ${med}\n    - Risk: ${risk}\n    - ${reason}`;
    }

    case "food_medication_interaction": {
      const food = String(d.food ?? match.matchedTerm ?? "food");
      const med = String(d.medication ?? "your medication");
      const reason = String(d.reason ?? "Consult your pharmacist");
      return `  • "${food}" may interact with ${med}\n    - ${reason}`;
    }

    case "medication_interaction": {
      const extracted = String(d.extracted ?? match.matchedTerm ?? "medication");
      const conflicts = String(d.conflictsWith ?? "your medication");
      return `  • "${extracted}" may interact with ${conflicts}\n    - Consult your pharmacist`;
    }

    default:
      return `  • ${match.kind}: ${match.matchedTerm || "Unknown match"}`;
  }
}

function isRawMatch(m: unknown): m is RawMatch {
  return (
    typeof m === "object" &&
    m !== null &&
    "rule" in m &&
    "details" in m &&
    typeof (m as RawMatch).details === "object"
  );
}

function extractMatchedTerm(m: RawMatch): string {
  const d = m.details ?? {};
  if (m.rule === "allergy_match") return String(d.allergen ?? "");
  if (m.rule === "dish_allergen") return String(d.matchedDish ?? d.allergen ?? "");
  if (m.rule === "cross_reactive") return String(d.matchedTerm ?? "");
  if (m.rule === "medication_interaction")
    return [d.extracted, d.conflictsWith].filter(Boolean).join(", ");
  if (m.rule === "supplement_medication_interaction")
    return [d.supplement, d.medication].filter(Boolean).join(", ");
  if (m.rule === "food_medication_interaction")
    return [d.food, d.medication].filter(Boolean).join(", ");
  return "";
}

function extractCategory(m: RawMatch): string | undefined {
  const d = m.details ?? {};
  if (m.rule === "allergy_match") return String(d.matchedCategory ?? "") || undefined;
  if (m.rule === "dish_allergen") return String(d.allergen ?? d.matchedCategory ?? "") || undefined;
  if (m.rule === "cross_reactive") return String(d.source ?? "") || undefined;
  return undefined;
}

function getRecommendation(riskLevel: string): string {
  switch (riskLevel?.toLowerCase()) {
    case "high":
      return "  Do not consume this item without verification.\n  Check ingredients carefully or ask staff/pharmacist\n  to confirm it's safe for you.";
    case "medium":
      return "  Proceed with caution. Consider timing of consumption\n  relative to your medications. Consult your pharmacist\n  if uncertain.";
    case "low":
    case "caution":
      return "  Low risk detected. Be aware of the potential issue\n  but this is generally safe with normal precautions.";
    default:
      return "  No known risks detected for this profile.\n  Always check ingredient labels for unlisted allergens.";
  }
}

/** Deterministic filename for text report download. */
export function textReportFilename(createdAt: string): string {
  const d = new Date(createdAt);
  const date = d.toISOString().slice(0, 10);
  const time = d.toTimeString().slice(0, 5).replace(":", "-");
  return `allergy-angel-check-${date}-${time}.txt`;
}
